import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MENUITEMS.MAIN.TEXT',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },
  // Admin Modules
  {
    path: '',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'feather',
    icon: 'monitor',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/dashboard/main',
        title: 'MENUITEMS.DASHBOARD.LIST.DASHBOARD1',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/dashboard/dashboard2',
        title: 'MENUITEMS.DASHBOARD.LIST.DASHBOARD2',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'Departements',
    iconType: 'feather',
    icon: 'monitor',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/departements/add-departement',
        title: 'Add departement',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/departements/alldepartements',
        title: 'All departements',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PROJECTS.TEXT',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/projects/allProjects',
        title: 'MENUITEMS.PROJECTS.LIST.ALL-PROJECTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/projects/addProject',
        title: 'MENUITEMS.PROJECTS.LIST.ADD-PROJECT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'My Mission',
    iconType: 'feather',
    icon: 'grid',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [
   
      {
        path: '/employee/mission/missions',
        title: 'Missions',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
     
    ],
  },
  {
    path: '',
    title: ' Missions',
    iconType: 'feather',
    icon: 'grid',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [
   
      {
        path: '/client/mission/missions',
        title: 'Demande Missions',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
     
    ],
  },
  {
    path: '',
    title: 'Mission',
    iconType: 'feather',
    icon: 'grid',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
   
      {
        path: '/admin/mission/allmissions',
        title: 'Missions',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
     
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.POLICYPAYMENT.TEXT',
    iconType: 'feather',
    icon: 'shield',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/Policy/paymentPolicy',
        title: 'MENUITEMS.POLICYPAYMENT.LIST.PAYMENTP',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      ]}, 
      {
        path: '',
        title: 'MENUITEMS.POSTE.TEXT',
        iconType: 'feather',
        icon: 'shield',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [
          {
            path: '/admin/Postes/Poste',
            title: 'MENUITEMS.POSTE.LIST.POSTE',
            iconType: '',
            icon: '',
            class: 'ml-menu',
            groupTitle: false,
            badge: '',
            badgeClass: '',
            role: [''],
            submenu: [],
          },
          ]},
  {
    path: '',
    title: 'MENUITEMS.EMPLOYEES.TEXT',
    iconType: 'feather',
    icon: 'users',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/employees/allEmployees',
        title: 'MENUITEMS.EMPLOYEES.LIST.ALL-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/employees/add-employee',
        title: 'MENUITEMS.EMPLOYEES.LIST.ADD-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/employees/edit-employee',
        title: 'MENUITEMS.EMPLOYEES.LIST.EDIT-EMPLOYEE',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
   
    ],
  },
 
  {
    path: '',
    title: 'MENUITEMS.LEAVES.TEXT',
    iconType: 'feather',
    icon: 'trello',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/leaves/leave-requests',
        title: 'MENUITEMS.LEAVES.LIST.LEAVE-REQUESTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
    ]
  },
  {
    path: '',
    title: 'MENUITEMS.HOLIDAYS.TEXT',
    iconType: 'feather',
    icon: 'coffee',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/holidays/all-holidays',
        title: 'MENUITEMS.HOLIDAYS.LIST.ALL-HOLIDAYS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: '/admin/holidays/add-holiday',
        title: 'MENUITEMS.HOLIDAYS.LIST.ADD-HOLIDAY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: '/admin/holidays/edit-holiday',
        title: 'MENUITEMS.HOLIDAYS.LIST.EDIT-HOLIDAY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.ATTENDANCE.TEXT',
    iconType: 'feather',
    icon: 'edit',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/attendance/billing',
        title: 'Weeks attendance',
        iconType: 'feather',
        icon: 'file-text',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
      {
        path: '/admin/attendance/attendance-sheet',
        title: 'MENUITEMS.ATTENDANCE.LIST.SHEET',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PAYROLL.TEXT',
    iconType: 'feather',
    icon: 'clipboard',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/payroll/employee-salary',
        title: 'MENUITEMS.PAYROLL.LIST.EMPLOYEE_SALARY',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/payroll/payslip',
        title: 'MENUITEMS.PAYROLL.LIST.PAYSLIP',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.JOBS.TEXT',
    iconType: 'feather',
    icon: 'award',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [
      {
        path: '/admin/jobs/jobs-list',
        title: 'MENUITEMS.JOBS.LIST.JOBS_LIST',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/jobs/candidates',
        title: 'MENUITEMS.JOBS.LIST.CANDIDATES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  // Employee Modules
  {
    path: '/employee/dashboard',
    title: 'MENUITEMS.EMPLOYEE.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myleaves',
    title: 'MENUITEMS.EMPLOYEE.MY-LEAVES',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/myprojects',
    title: 'MENUITEMS.EMPLOYEE.MYPROJECTS',
    iconType: 'feather',
    icon: 'database',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/employee/mytasks',
    title: 'MENUITEMS.EMPLOYEE.MYTASKS',
    iconType: 'feather',
    icon: 'command',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Employee'],
    submenu: [],
  },
  {
    path: '/client/dashboard',
    title: 'MENUITEMS.CLIENT.DASHBOARD',
    iconType: 'feather',
    icon: 'airplay',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },
  {
    path: '',
    title: 'MENUITEMS.PROJECTS.TEXT',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [
      {
        path: '/client/projects/allProjects',
        title: 'MENUITEMS.PROJECTS.LIST.ALL-PROJECTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/client/projects/addProject',
        title: 'MENUITEMS.PROJECTS.LIST.ADD-PROJECT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

    ],
  },
  {
    path: '/client/billing',
    title: 'Attendance',
    iconType: 'feather',
    icon: 'file-text',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },

  {
    path: '/client/settings',
    title: 'MENUITEMS.CLIENT.SETTINGS',
    iconType: 'feather',
    icon: 'settings',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Client'],
    submenu: [],
  },

  // Common Module
  {
    path: 'calendar',
    title: 'TimeSheet',
    iconType: 'feather',
    icon: 'calendar',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: 'badge bg-blue sidebar-badge float-end',
    role: ['Admin', 'Employee'],
    submenu: [],
  },
];
